### ISSUE TITLE
New Devices

### ISSUE THREAD

**Issue by ajhodges** [hackgvl/trolley-tracker#105]
Per our discussion today, I think we should look in to getting new devices. Preferably a phone (cheaper) and one that has a good GPS and Verizon LTE compatibility.

The Moto E immediately comes to mind, and can be had brand new for $47.99 here: http://www.walmart.com/ip/Verizon-Moto-E-Prepaid-Smartphone/44052006

The Moto E is more than capable for our purposes and the price point is really attractive. The only issue is that Verizon has a policy that says you can't use prepaid devices on postpaid plans unless the phone has been active on a prepaid plan for longer than 6 months.

The loophole to this is that if you just ask Verizon for an activated sim card, they don't know what device you're going to use it in so they can't really enforce this.

I'm ready to pull the trigger and buy one of these puppies and rig it up so it powers on/off when it is unplugged, I just need @greenlinktransit to verify that they can get an activated LTE micro-sim card from Verizon for each of the trolleys.

Source: https://www.reddit.com/r/verizon/comments/36pprc/which_prepaid_phones_able_to_be_put_on_postpaid/

Our other option is to buy a cheap used Verizon post-paid phone. But I would really prefer the Moto E.

**Comment by bikeoid** [comment]
If we can install the devices as hidden and auto-on, it shouldn't need security updates since people won't be browsing the web on it.  

One other thing if it's hidden - the GPS signal is much weaker than cellular signals, so it might not work acceptably if mounted under the foil of the roof panel or under a metal dash.

I'm good with either this or a tablet - this phone will certainly be easier to finance.

**Comment by ajhodges** [comment]
I'm gonna backtrack a bit - apparently that model of the Moto E is not rootable, Verizon has locked down the bootloader. I will need root to modify the phone to turn on when it is plugged in.

I will do more research on devices. In the meantime I would still like to know what the device activation process is like with your contract with Verizon. If the modems on the trolley already have micro sim cards, it could be as simple as swapping it over to our new device. Otherwise, we will need to get sim cards from them. They might want to have the device physically there to issue a new sim card too, due to their policy with using prepaid phones.

@bikeoid those are all good points, though we will want to keep auto updates on (for apps at least) for pushing new versions of our beacon app. Hopefully that layer of metallic foamy stuff lining the roof won't affect GPS too much but we'll have to do some testing with it.

**Comment by greenlinktransit** [comment]
It would be helpful if you guys gave me a specific list of questions for Verizon.  I could send them around internally, but I'm guessing that no one would have a clue.

**Comment by ajhodges** [comment]
For you guys:
- How married are you to Verizon? Contract-wise and otherwise. They are pretty expensive, as yall have seen, and are very restrictive as to what devices they allow on their networks (and even what you can do with those devices).
- Does the modem you have use a SIM card? Probably not because it seems to be a 3G device.

For verizon:
- Is 4G LTE service included in your current contract?
- If we have existing Verizon LTE devices (say we have them already but we would probably buy them off ebay), what is the process for activating them under your account? Can we just get some activated SIM cards?
- What Android devices are available to purchase via Verizon and at what cost?
  - Do you get a subsidized contract price?
  - Up to how many devices? 
  - If you have to buy them outright, what is the cheapest device? 
  - Any refurbished options?

**Comment by greenlinktransit** [comment]
I'll forward these questions on the appropriate people and will let you know when I hear back.

**Comment by greenlinktransit** [comment]
Guys....I forwarded Adam's questions to our IT department (they control our Verizon contract) and here's their response...
****************
Grant,
I was talking with Tristan yesterday and he will be working closely with you guys.  In answering some of the questions below, perhaps it will give us some options.  First, before I answer those, here was Tristan’s idea to diagnosis this issue.    He was going to take an existing Android phone that we have which has Verizon service.  He would like to install the tracker app on the phone and run the phone at the same time as running the tablet.  We are trying to pinpoint if the issue is with the modem versus the Verizon service.  You should be hearing from him today about this.

Our contract is the same with Verizon as it is with AT&T and Sprint.  All three are driven by the state contract.  I was not involved in the original setup so I am not sure why we are using machine to machine service for these tablets, however, I do know that we could get data enabled tablet from Verizon fairly inexpensive which is mandated by the state contract to have an unlimited data plan. 

If Tristan’s test works and his phone proves to be more stable than the tablet going through a machine to machine modem I propose that we turn off all the services associated with these modems and order two data enabled tablets.  That would eliminate all the overhead associated with the connection now. 
*******************
I think it would be easiest if someone sends Tristan a GitHub invitation so he can chime in on this thread.  His email address is tkenney@greenvillesc.gov.  He also just requested to be a Beta tester in the yeahthattrolley.com site.

**Comment by greenlinktransit** [comment]
Also, I have no idea if this is relevant at all but in working with some colleagues from other transit systems someone suggested that we look into Transitime (http://www.transitime.org/home.html) and see if we can use some of their concepts for our own system.  Apparently they won some hackathon award -- http://devpost.com/software/transitime-open-source-real-time-transit-information.

**Comment by dacohenii** [comment]
I'm happy to volunteer my old [Nexus 5](https://en.wikipedia.org/wiki/Nexus_5) again (we used it in the beginning for testing purposes, but it was decided that we'd use the tablets instead). It won't work on Verizon, however.

@greenlinktransit: It should be no problem adding Tristan to the organization; however, he must first [sign up](https://github.com/join). Once he's signed up, let us know, and one of us can add him.

**Comment by greenlinktransit** [comment]
I sent him the yeahthattrolley.com link, so he should have already signed up (or will be very soon).

**Comment by ajhodges** [comment]
:+1: good addition to the conversation. I just would like to let the IT guys (Tristan?) know that we would like to move away from having a tablet on the dash at all and instead mount the phone in the overhead compartment where the router currently resides. To do this, we need a phone that I can root and dig in to the system partition so I can boot the phone up whenever it is "plugged in" (key in the ignition). Then we don't have to worry about drivers forgetting to turn the device on/off.

But other than that it sounds like we are on the same page here. Nexus 5 would be great, Moto E would also be great because of how cheap it is. If GreenLink already has access to AT&T and there is no legal/financial downside to switching service for the trolleys over to AT&T and purchasing a couple Moto E's, it would make my life a lot easier!

Please keep me posted on how the phone test goes. We were measuring ~500kbps up/down on the trolley so I have a feeling that a phone with a 4G connection is going to be a lot more consistent.

I will have to whitelist Tristan's email before he can download the beacon app (which is separate from the client), and we will have to work something out so we don't have his phone showing up as a "live trolley" on the map. @bikeoid what do you think? Should we have him point his phone at the old API?

**Comment by agautsc** [comment]
@greenlinktransit Tristan should have just received a Beta invite for the public Android app. Like @dacohenii mentioned, if Tristan wants to be part of the GitHub org just have him create a GitHub account and let me know what that email is and I'll add him to the Code for Greenville org.

**Comment by bikeoid** [comment]
Re: testing - I'd agree that it is better for him to use the dev server at http://yeahthattrolley.azurewebsites.net for the Server IP on the beacon.   He can leave it on and use the DB Visualizer to confirm complete system operation.

**Comment by greenlinktransit** [comment]
@agautsc @dacohenii Tristan's GitHub username is tkenney-gvl and his email address is tkenney@greenvillesc.gov

**Comment by agautsc** [comment]
He's been added :wave: @tkenney-gvl

**Comment by greenlinktransit** [comment]
I have another request -- could you please add Mike Blizzard from IT, as well?  His username is mblizzard-gvl

**Comment by agautsc** [comment]
@mblizzard-gvl has been added. :wave:

**Comment by tkenney-gvl** [comment]
Hey guys,
sorry it took me a while to get on, we were pretty busy here today. My initial thought when Grant approached us was that we could just keep the existing system and run a phone (since he had one that was just reclaimed - a Galaxy S4, Verizon) that we could use to test along side the existing setup to verify that it was a connection issue. I can definitely root it to make it usable for the auto-launch if that is the route the OP wants to take. 
Thanks to everyone willing to donate hardware, however, the City will provide its own hardware and choose its own carrier primarily since we will be supporting this in the future.
For now, though, I'll get the S4 rooted per @ajhodges suggestion and get the admin tracker app installed, so we can test the connectivity issue.

Long term solution if the connectivity issue is resolved with the S4 would be to have two new dedicated mobile devices provided by the City.

**Comment by ajhodges** [comment]
Hey Tristan! Sorry for the confusion, I think you should go ahead and do your parallel test! Should be helpful in diagnosing the issue.

As for the S4, we could use a S4 no problem. The reason I wanted to nail down a long-term device ahead of time is that it will take some hackery to make the device boot up when it is plugged in, and because the technique I am going to use is device-specific, I'd rather not have to figure it out twice. So maybe we can just use the S4 to test the connectivity (so there's no need to root) and then you guys can choose whatever device you'd like - provided that the bootloader is unlockable.

Also I need your gmail (@tkenney-gvl) so I can whitelist it for the app.

Thanks!

**Comment by tkenney-gvl** [comment]
Sounds great. I totally agree that we'd only need to do that custom hackery once (or a few times as device lifecycles happen). :) I'll email you from my my test gmail account so you can add it to the whitelist. Thanks!

**Comment by ajhodges** [comment]
I added you. Please make sure you go in the settings of the app and change the server URL from api.yeahthattrolley.com to yeahthattrolley.azurewebsites.net before enabling background collection! I think we need to send you the credentials to use too (username is hard coded). @bikeoid can you send those in an email to @tkenney-gvl? I can't remember them...

**Comment by tkenney-gvl** [comment]
Cool, thanks!

**Comment by tkenney-gvl** [comment]
Everyone,
Thanks for all the info and help. I just wanted to update everyone that I was able to get the agent loaded on the S4 this morning and I checked on the test tracking page and it shows up. Our next step will be to get it in the Trolley (probably Trolley1) and have it ride along, so we can do some testing and watch them side by side and see if the tablet drops and the S4 doesn't or if they both drop at the same time.
Also I wanted to let you know of a possible issue, where when I was transitioning between mobile data and Wifi and I happened to launch the consumer app on my LG G3 it kept crashing the app. I'm not sure if that's default behavior or because of the underlying android system calls that happen when the app is launched. Also when I turned off any mobile or wifi it kept crashing the app too. I'm wondering if we could maybe add a function to allow the app to still launch, and just do a quick check for connectivity and if not, pop up a redirect to the settings to enable data/location/wifi or something. Might be more headache with coding than what it's worth, but I  just thought I'd make a note here to let you all know. :)

**Comment by bikeoid** [comment]
It looks like the test beacon (Trolley 3 on the dev server) stayed running all weekend.   Let me know before you run the test on a real trolley;  especially if it's tested in the same location where it will be finally installed.   I'd like to record the path to confirm that the GPS isn't lost, causing it to fall back on wifi + cellular accuracy only.

**Comment by tkenney-gvl** [comment]
@bikeoid I also saw that it was up pretty much all weekend. At this point I've heard back from the Fleet Services from the Trolley and we'll be getting them the device tomorrow for them to install in the Trolley (I'll find out which one tomorrow). Hopefully they'll get it installed before this weekend's Trolley use so we can watch them this weekend. Once I know which Trolley they'll be installing it on, we should be able to compare the route from the active trolley with the route on the test server and make sure that they're coinciding and then can also check for stability.

**Comment by tkenney-gvl** [comment]
Hey Guys (and Gals),
The S4 is live and mounted in one of the trolleys. Since the fleet management doesn't use "Trolley 1" and "Trolley2", as they have other designations for them, I'll be looking at it over the lunch period when the trolleys are running today. I'll be able to tell probably pretty quickly which trolley it's on and I'll post it here as well. Thanks again.

**Comment by agautsc** [comment]
:clap:

**Comment by tkenney-gvl** [comment]
At this point I'm not seeing any trolleys running in the Android client Trolley Tracker app, but I'm seeing the positions of the one Trolley that has the S4 (from the test DB URL). It was pretty accurate as I watched it pass by City Hall and I was looking at it from the office, so I know at least that the tracking is working for the S4 - we'll just need to see how consistent it is.

**Comment by bikeoid** [comment]
This looks great!    When the S4 is on the trolley, it's fine to point the beacon to the real server.   Everything remains the same in the settings except for the "Server IP", which is set to api.yeahthattrolley.com .

I noticed that the S4 on the development server was moving so I watched it for part of lunch.    There were some GPS wobbles around the downtown buildings, but it is more than adequate for what we need to go live, as long as it runs consistently.

**Comment by ajhodges** [comment]
How is the S4 mounted right now, out of curiosity? Does the driver turn it on/off?

We've been using the last digit of the license plate to identify the trolleys right now, so we have 5 and 6. So you'll also need to take a look at that and change the ID in the app accordingly, and then delete the agent from the tablet. Then we should be good to go! We could use a different method of identifying the trolleys, that's just the only visual difference between the trolleys we could really find at the time.

Hopefully we see continue to see a higher level of consistency on the S4. I've been meaning to do some work on the agent app to try to improve reliability, I just haven't gotten around to it :(

**Comment by bikeoid** [comment]
FYI - I'm also mirroring Trolley 3 from the Dev server to the production server so that those who have signed up for the Trolley Tracker beta will have something to see and test with.

**Comment by tkenney-gvl** [comment]
@ajhodges As far as I know it's mounted right beside the tablet on the dash. The drivers are doing the exact same thing with it as with the tablet (turning it on/off with the trolley power).
@bikeoid I'll be heading over there sometime today and will be updating the S4's tracker settings to go directly to the production server's address. I'll be leaving it as Trolley3, though, since we want to run it side-by-side with the real Trolley (5 or 6) to test for stability.
Thanks again for all your work and help! :)

**Comment by bikeoid** [comment]
I collected some good data from this weekend's run.  The first shows all tracks - the track accuracy was very good for our purposes.  This is all paths run over the entire route:
![t3path](https://cloud.githubusercontent.com/assets/75929/11192113/2ba47cdc-8c6d-11e5-8d36-33f0c8a8ae05.jpg)
The single detour on Academy Street was a real path.  There was only a single 'shortcut' trace from Park to N Main, but that isn't a big problem.  Here is a closer view against city building satellite views:
![t3pathwithsatellite](https://cloud.githubusercontent.com/assets/75929/11192144/54ee433e-8c6d-11e5-8926-fd376feaa58b.jpg)

Unless the new device will be mounted in a location with more metal shielding, we should not need any more testing.  Device 3 did not show up on Friday night, so the biggest problem may still be getting it started consistently.

If the mounting has been finalized, I'd recommend that we proceed with the device adaptation to automatically turn on when power is applied, and assuming that it can be attached to 'ignition power'.   We can run testing while modifying to confirm that it can start by itself many times in a row without failing.

The tablet was only online for a few minutes on Friday.

**Comment by agautsc** [comment]
Super helpful data @bikeoid :clap: I might get that top image as a tattoo. (I'm not really getting that as a tattoo, but it would be some cool piece of art.) 

I agree with switching over to phones. It seems like the tablet use is getting worse. If there are two phones that the city or Greenlink has and can use let's do it. If we need to have some type of fundraiser to buy root-able phones I bet we could get that done fairly quickly. Just let us know what we need to do.

**Comment by ajhodges** [comment]
That looks pretty accurate to me! Thanks for doing that visualization.

I think the 'ignition power' issue was mostly just that when we first
tested it, we left the key in the ignition and the power isn't cut to
accessories until the key is removed from the ignition. Assuming the keys
aren't left in the ignition, that should be more than suitable.

Unfortunately I've been doing more research in to Verizon devices and it
seems like Verizon is very particular about having devices with unlocked
bootloaders on their network, and so there are very few devices (if any?)
that have unlockable bootloaders. A cursory search reveals that the Nexus 6
and Moto X (2015) version are some of the only phones that are currently
able to have their bootloader unlocked (along with other 'developer
edition' phones).

If we are stuck with Verizon S4s, then the 'auto-on' feature might not be
possible as I'm going to need an unlocked bootloader to modify the charging
animation to trigger a boot. Some of the older Verizon S4 OS versions were
unlockable, but chances are these S4s have been updated and the exploits
have been patched.

**Comment by bikeoid** [comment]
@tkenney-gvl: what are the plans for the weekend?    I think we could have good results if we replaced the tablets with a mobile device, unless final mounting needs to be tested.

Also, will both trolleys be running this weekend?

**Comment by greenlinktransit** [comment]
@bikeoid I'll check with Maintenance and OPS on the trolley schedule for this weekend.

**Comment by greenlinktransit** [comment]
@bikeoid Per OPS....we're still waiting for one of the trolleys to get back from the body shop.  Apparently it's supposed to be back today, but I heard the same story a couple weeks ago. I'll give you an update tomorrow.

**Comment by tkenney-gvl** [comment]
Nice visualization @bikeoid! As far as I know, the City will plan on providing the final equipment (the S4 was just for testing), so we'll do some research and make sure we get some devices with unlockable bootloaders for the final mounting.
I tried getting the S4 on the production server the other day, but the data Mike Nice gave me to plug in showed "Unauthorized" in the main window on the tracker agent. I'll email him to get the complete info for when we get the new phones. Thanks!

**Comment by greenlinktransit** [comment]
FYI -- we got the 2nd trolley back last night from the body shop and it broke down on its first loop.  Back to the shop it goes....

**Comment by agautsc** [comment]
They are being bought up fairly quickly, but there are still some Nexus 5's (last years model not the 5X) that are being sold online for around $200 each. I'll get @ajhodges to confirm, but I think those would work for all our needs.

**Comment by ajhodges** [comment]
Unfortunately I just looked it up and the Nexus 5 won't work on Verizon,
but the 5X will.

**Comment by mblizzard-gvl** [comment]
Hi All,

I've been sitting tight and keeping an eye on the conversation but haven't contributed.  Thank you all for you for the hard work you have put into this.  We are ordering two Nexus 6's from Verizon today.  They should arrive early next week which will allow us to configure the device and install the app before we head out for Thanksgiving.  Either myself or Tristan will update everyone once we have them in hand.

Thanks again for all the input.

Mike
City IT Department

**Comment by agautsc** [comment]
Woot!

**Comment by bikeoid** [comment]
This is great news!   I'll disable the monitoring system for now until the new devices are installed.

**Comment by greenlinktransit** [comment]
Also a heads up that we will be returning all of the RouteMatch equipment on the Trolleys once the new phones come in.  This includes the Samsung tablets, mounts, cases, and chargers.

**Comment by jeremywight** [comment]
Thanks Mike! Awesome!

On Fri, Nov 20, 2015 at 11:27 AM, greenlinktransit <notifications@github.com

**Comment by greenlinktransit** [comment]
FYI -- one of our supervisors said that the trolleys were appearing and disappearing on the Trolley Tracker all weekend despite the tablets being powered on.  Hoping these snazzy new phones will be more reliable.

**Comment by bikeoid** [comment]
How do the new phones look?   Let us know if you want any help on the special bootloader for auto power on/off (I haven't done one of these myself before)

**Comment by agautsc** [comment]
I second @bikeoid Let us know if we can help get the phones installed this week. I'm around and available if needed.

**Comment by mblizzard-gvl** [comment]
We have the phones in hand now.  Tristan will be working with everyone to get the app installed and configured hew will also work with the fleet shop to get the units mounted.  If everything goes as planned, they should be live this week.

**Comment by ajhodges** [comment]
I won't be able to tinker with the auto power on/off stuff (off will just need an app/I can add it to the agent, on will need some digging) without access to a device. I can probably get started by poking around a rom I downloaded off xda-developers but I'll definitely need to use one of the devices to test, unless @tkenney-gvl was going to take a stab at it.

FWIW I was going to follow the general approach here: http://stackoverflow.com/questions/4169387/how-to-make-android-device-boot-when-power-is-plugged-in

**Comment by tkenney-gvl** [comment]
Hey guys, sorry for the delay. I wasn't able to get it taken care of before Thursday. Right now I'm working on getting the bootloaders unlocked and the devices rooted. Once that's done I'll go ahead and set the tracker agent to autostart when the device is powered on. Since the devices have battery, I'm honestly not sure how we'll be able to use the ignition-on feature. But if we can train the attendants to turn the devices off when the Trolley is done running and turn them on when they turn the Trolleys, then having the app autostart would make things a lot easier. :) Anyway, I'll let everyone know when the devices are installed in the Trolleys. Thanks again for all the help!

**Comment by ajhodges** [comment]
The app is already set to autostart when the device is powered on so we
should be good there. The premise of the ignition-on feature is that we
hook in to the charging screen (that pops up with a battery indicator when
you plug in a powered-down device) script and make it reboot the device, so
it is effectively powering on the device whenever it is plugged in. More
details in the stackoverflow link in my last comment.

We aren't sure how much of our issues have been due to drivers forgetting
to turn the tablets on/off but Grant has already had a few training
sessions with them. Not sure how effective that is. The idea behind the
auto-on/off feature was that we could mount the devices in a hidden spot
(the overhead compartment is a good candidate) and have them
out-of-sight/out-of-mind. Less likely to be stolen too.

**Comment by tkenney-gvl** [comment]
Thanks to my supervisor, we found a fastboot command that allows the system to turn on automatically when power is applied (just tested and it works!). We still haven't solved for shutdown, but we're testing what will happen with a fully drained battery and the autostart. If that works, then I think we have all the pieces down so that when they turn on the Trolley and the power is sent to the device it should turn on automatically and then load the Trolley Tracker Agent app (just in case the event hook doesn't do the full trick). Hopefully that will solve all the hiccoughs. :)

**Comment by ajhodges** [comment]
That's awesome! Even easier than I expected. Give your supervisor a high
five for me. I believe there are apps that will do the shutdown or I am
pretty certain that I could package that functionality in with the agent in
just a few lines of code. Fingers crossed that it all works smoothly. It's
always a win when you can eliminate human error from the equation.

**Comment by greenlinktransit** [comment]
It sounds like you guys are on the right track.  For what it's worth, it would save us many headaches if we can completely remove the human component of turning the phones on/off during each run.  But you know that already.

**Comment by jeremywight** [comment]
Definitely agreed. +100 on no human interaction needed :)

**Comment by ajhodges** [comment]
Good news, I just implemented a feature in the agent that will shut down the device when it is unplugged. The two caveats are that it is opt-in (you will need to enable it in the settings for each device) and that it requires root. If you have a root management app on the device like SuperSU, you will need to grant the agent root access. It will request root access the first time you enable the shutdown feature and then unplug the device. Hope this is the last piece to our puzzle!

The update should be available via the play store in an hour or so. Which reminds me, are the devices configured to download new updates automatically? That would make updating the app pretty painless in the future.

**Comment by ajhodges** [comment]
One more point, this new feature is going to make it so if the drivers
unplug the USB cord to charge their own phone (as they've done in the
past), our device will be powered down. Just something to think
about/another reason to hide the device

**Comment by tkenney-gvl** [comment]
SuperSU is on both Nexi (?), so I'll add the tracker to the root list. As far as I know they are set to do the automatic updates, but I'm not sure how the newer Android "oh, you're not on wireless, so maybe we won't download the updates" feature will affect it. I know that it's a small app, so it may do the auto update. I'll check into it a bit more and hopefully there's an option in the app to specifically get the updates automatically instead of requiring manual intervention. Worst case, we can set up something on our end to go to the shop and do maintenance once a month or so and get all the system and app updates. :)

**Comment by ajhodges** [comment]
Sounds good! Another thought, I think there is WiFi around the maintenence
bay. So if we are 100% sure that it's a unique SSID and not used anywhere
else downtown (don't want to go down that road again), then maybe that
could trigger the updates?

**Comment by tkenney-gvl** [comment]
We got the Nexus 6 phones over to the trolleys and they are being installed. As of right now, when the drivers turn the trolleys on, the auto-on feature kicks in and the Nexus 6 will boot (tested), then automatically launch the app as soon as the OS boots (just a precaution, since @bikeoid mentioned that he had to do that before on the tablets on occasion). The wifi is also on and automatically set up to connect to our Internal City Wifi network, which is over at the Shop. I tested and as soon as I had it back on wifi the tracker agent updated on both phones, so we will have to leave the wifi on. With the new version of the tracker, I was able to set the auto-off feature and also grant root permissions and have tested both phones when the power was unplugged. That worked, too, so hopefully at this point everything should be as automated as possible and working for tomorrow's route as soon as they're installed.
Initially we're having one mounted on the dash and the other one in the other trolley mounted in the overhead bin, and we'll see if there is a difference in signal quality between the two trolleys. If they both function great this weekend, then we'll be able to put the dash mounted on also in the overhead bin and make it super clean. :) Thanks again for everyone's help with this! :+1:

**Comment by agautsc** [comment]
:trolleybus: :dancer: :fireworks: :tada:  Super exciting

Worth a mention, our belief is part of the problem with the tablets was they were jumping off the internal trolley wi-fi and connecting to other free downtown hotspots and even the other trolley wi-fi. I doubt this will be a problem with the phone, but it we do have connection problems it might be worth turning off wi-fi as a troubleshooting step.

:fireworks: :trolleybus: :tada: :trophy:

**Comment by ajhodges** [comment]
Very exciting, it all sounds promising! Thanks for all your help @tkenney-gvl, I think we're close! :tada:

**Comment by greenlinktransit** [comment]
@tkenney-gvl Thanks for your hard work on this, Tristan!

**Comment by bikeoid** [comment]
That's great news!    I'll keep an eye on the accuracy over the weekend and should be able to generate the same type of report as last time for each vehicle.

**Comment by jeremywight** [comment]
This is great news. Look forward to checking it this weekend!

**Comment by ajhodges** [comment]
@tkenney-gvl so we should be seeing two trolleys right now? Looks like trolley 6 is up but trolley 5 is MIA. Which one was the dash-mount? Excited to see these new nexuses cranking out some lat/lngs!

**Comment by ajhodges** [comment]
So the tracker is still running on the trolley even though it's been parked
for a while now. It just occurred to me that we need to make sure the keys
are removed from the ignition after the drivers turn the trolleys off.
Otherwise the accessories (including our phone) are left powered on and
will drain the trolleys battery. Not to mention our app will run overnight.

Doesnt really affect the reliability of our app (I'm pretty sure Mike can
code something to mark a trolley as offline if it hasn't moved a
significant amount in >30min) but it sure will suck to have to jump the
trolleys every morning.

**Comment by bikeoid** [comment]
Trolley 5 was last seen at city hall, so it's never obtained a GPS fix from the trolley.

**Comment by greenlinktransit** [comment]
I've alerted OPS about the new devices and have asked them to keep an eye on the tracker over the next couple weeks to see if there's a certain trolley that's working better than the other.  I've also asked them to give me a heads up if a trolley ever goes out of service, is late, etc.  I know that the trolley schedule is going to be weird tomorrow with the parade -- I believe we're decorating both trolleys in the morning, so we probably won't have anything to look at until after the parade is over.

Lastly, we have a new General Manager of OPS starting with us on Monday.  He's young and understands technology very well.  Once he gets settled in, I'd like to set up a short meeting so we can brief him on the Trolley Tracker and how he can assist. 

Thanks again for everyone's hard work on this.

**Comment by agautsc** [comment]
I separated out the two "bugs" we tracked last night (Thursday 12/3) into unique issues.
