### ISSUE TITLE
Feedback: Only one trolley showing: Jan 2

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#123]
I have some feedback to provide about my application using experience:

At around 7:30 P.M. I was driving north on Main just south of Stone when I saw a trolley make the left onto Stone. I checked the trolley tracker and it only showed one trolley down near Flour. Not sure what was going on

**Comment by greenlinktransit** [comment]
Uh oh.  Anyone else check the Trolley Tracker on Saturday? I haven't heard of any problems on our end.

**Comment by ajhodges** [comment]
Was this definitely on saturday? Every time I checked throughout the weekend it looked good. Although one time I saw one trolley was running and the other was sitting in the greenlink bay. Can't remember when

**Comment by agautsc** [comment]
Got the Email on Jan. 2. Strange. We didn't get any warning text either.

**Comment by bikeoid** [comment]
The paging system was on, so it definitely wasn't out for any length of time.   Also, I ran a query of the travel path from 7:15PM to 7:45PM on Jan 2 and found that both trolleys were working, and had traveled most of a complete trip during that period - no jumps.    So both the beacons and server were working.

Just theorizing - it could be partially due to a client connectivity - if the device is awakened and the app comes up, it may need to establish an Internet connection before the next update.    That could have been delayed for a few seconds due to trying to connect to a nearby open WiFi, etc.    Since they were driving, they may not have left it up long enough to get an actual update.

Perhaps for a V2/V3 app enhancement - remove the trolley positions from view if the last update has been more than X seconds ago, or upon first re-opening the app?

**Comment by ajhodges** [comment]
@bikeoid that is definitely a possibility. I can add that check in the android app no problem. Though it should really only flash for <5secs before it is updated (unless there are connectivity issues).
