### ISSUE TITLE
Feedback from Brian Beers

### ISSUE THREAD

**Issue by agautsc** [hackgvl/trolley-tracker#125]
_Brian's Email_
I have some feedback to provide about my application using experience:

Schedule is useless, it lists all routes on all days.

_My Response_
Thanks for the feedback. I've got a couple questions that might help us understand things more.

1) Are you using the iOS or Android app?

2) Can you explain what you'd like to see from the schedule? Our thought for showing the schedule is that the trolley only runs during certain times so if folks check the app not during those times they need to see something and giving them the times the trolleys are running might be helpful.

This might not be as helpful as we believe. What would be helpful to you?

Thanks,
-Adam

**Comment by greenlinktransit** [comment]
I received similar feedback from one of our drivers.  He said that the riders are loving the app but that they are completely confused by the schedule page.  Apparently one of our passengers was waiting to get picked up at the Kroc Center because the schedule page mentions the Kroc route that was used for Fall for Greenville.  To simplify, you might want to remove the current verbiage and replace with the following:
*************************************
Regular Service Hours:
- Thursday: 6:00 pm - 11:00 pm
- Friday: 11:00 am - 2:00 pm & 6:00 pm - 11:00 pm
- Saturday: 10:00 am - 11:00 pm*
- Sunday: 1:00 pm - 8:00 pm*

*Please note that the Trolley will service Heritage Green on Saturdays & Sundays, and will also service the Bon Secours Wellness Arena beginning 60 minutes prior to the event time (only for events on Thursday - Sunday).
***********************************

**Comment by bikeoid** [comment]
Re: Schedule page - now I see that something went wrong in the IOS app schedule page; it lists every route X every time slot, rather than just the active schedule.
