### ISSUE TITLE
Marketing flyers

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker#137]
Merchants downtown are happy to be able to answer questions about the trolley now by directing them to the trolley tracker App.   But they also wish for a marketing flyer, a window posting, or something that would directly send people to the app.   

  Is anyone pursuing this now?
  If not, is this something that we can put together?

**Comment by Linktheoriginal** [comment]
There's a bunch of places we could use stickers as well as flyers.

**Comment by loriramey** [comment]
Happy to help with this. I see that David Siglin has also joined the Meet-Up group and is slated to come on Tuesday. He's a great graphic designer so if he's interested in taking on the design, I'll happily hand that over. But I'll see what ideas I can come up wth to get us more visibility downtown. 

Does anyone have the original art file for the T.T. logo?
![trolleytracker_logo 1x](https://cloud.githubusercontent.com/assets/19319958/15204963/8d516e9a-17e1-11e6-9a7c-b4541e9887c5.png)

**Comment by loriramey** [comment]
Some ideas:
- Window clings would be nice because businesses wouldn't feel quite so committed to the experiment as they would with an actual sticker. But they're more expensive, around $10-15 each for one of decent size, like 6"x6".  On the upside, a few strategically placed window "ads" for the Trolley, or a "TROLLEY STOPS HERE" window cling at key stops with a blurb for the app might be worth the money. 

- Clear stickers are more pricey than their counterparts, around $1 each and usually you have to order 100-250 in a batch.  Probably not worth the expense.

- Regular stickers can be pretty cheap.  A quick search suggests a 4x6" sticker would cost us about 40c each if we ordered 100 of them. (Economy of scale is always true for stickers - it's cheaper per piece to order a whole bunch but you have to put all that money into the order up front for a large quantity.)

- Rack cards:  These would fit the tourist info racks that many businesses have downtown.  I usually use NextDayFlyers.com when I need quick, cheap, good quality printing and they never disappoint.  We could  get 1,000 rack cards for under $100 (if the back is printed grayscale/front is in color).  That's not a bad way to start spreading the word.  If the downtown hotels etc would place the T.T. literature in their racks, I think the tourist crowd would have a better chance of hearing about us.

**Comment by loriramey** [comment]
As for locals and other advertising, there are probably ways to get the word out.  Strategic location seems to be key here.  The entrance to Falls Park (near Spill the Beans) is a huge magnet for visitors local and from far away.  The ONE plaza (near SIP/Anthropologie/Methodical) sees a lot of traffic.  The ballpark has thousands of people come through each summer.  Targeting each of those somehow would accelerate getting the word out.

what about 
- asking the Drive what we'd need to do to get some kind of shout-out at their games?  We might need to sponsor something, but maybe they'd be willing to contribute to better downtown transportation just as a gift to the community
- finding a way to get the T.T. app promoted within the Falls Park entrance area? Not sure how, but I bet we can brainstorm! :) 
- guerrilla campaign to TT sticker every downtown map plaque?  That'd probably get us in trouble. :) If they care.... Maybe the City doesn't care?...?

**Comment by bikeoid** [comment]
Great ideas - Re: ball game: many people already ride the trolley, so posting something in there on the rider information board behind the driver would work.   And I'd hope that the Drive would give a free shout-out during the game, and maybe even an occasional scoreboard display slot.

Another logical place would be the existing signs at the stops.   Right offhand, I don't see an easy way to overlay part of the sign with our info even if we got permission.   Logically it would be an addendum below the existing information.  
![dscf6180](https://cloud.githubusercontent.com/assets/75929/15234234/8829caa6-187d-11e6-812f-4796be499445.JPG)

**Comment by greenlinktransit** [comment]
We have a lot of requests for Trolley maps and brochures from the downtown hotels.
What about a giving flyers in acrylic frames for hotels to have on their check-in counters?

**Comment by ajhodges** [comment]
Love the discussion and ideas. @greenlinktransit are you able to attend our meetup on Tuesday? Sounds like we are going to have a lot to discuss in the way of marketing and I think it'd be great if you could make it.

http://www.meetup.com/Upstate-Code-for-America/events/230502643/

**Comment by greenlinktransit** [comment]
I can’t attend Tuesday evening due to prior commitments, but would be happy to meet Wednesday if someone wants to get me up to speed.

Thanks!

[COG_Color_Side]

Nicole McAden
Marketing and Program Specialist | Greenlink
nmcaden@greenvillesc.gov<mailto:nmcaden@greenvillesc.gov> | www.greenvillesc.gov<http://www.greenvillesc.gov/>
office: (864) 298-2756 | fax: (864) 467-5006

**Comment by loriramey** [comment]
[flyer mockup.pdf](https://github.com/codeforgreenville/trolley-tracker/files/268455/flyer.mockup.pdf)
So .... when I sat down to do a quick flyer mock-up (thinking of the check-in counters at hotels, etc), I realized the Trolley map already has a lot of what a business would want to display .... so I added a box at the bottom right to advertise the app .... then realized there's already an app advertisement on the map!! 

- Perhaps the main push for hotels, downtown businesses needs to be simply giving them piles of the maps?  
- For trolley signs and such, adding the "Get the app" sticker might be sufficient?  
- Also window clings or clear stickers. 

I see pros/cons of each of these. Let's discuss tonight. :)

**Comment by greenlinktransit** [comment]
We have provided stacks of brochures/maps in the past – and that’s what requests are for.
However, maps get thrown away, and we would like to go “green” and have something that pushes folks to the app or to our website instead. Open to ideas!

[COG_Color_Side]

Nicole McAden
Marketing and Program Specialist | Greenlink
nmcaden@greenvillesc.gov<mailto:nmcaden@greenvillesc.gov> | www.greenvillesc.gov<http://www.greenvillesc.gov/>
office: (864) 298-2756 | fax: (864) 467-5006

**Comment by loriramey** [comment]
Pricing - stickers 
Many online vendors do custom stickers. I was working on NextDayFlyers (for something else) and noticed they do vinyl stickers for a good price.  
2x2" - 100 for $25; 250 for $37. 
3x3" - 100 for $50; 250 for $86

Problem w/stickers is price goes up rapidly as sticker gets bigger - but based on the photo of the sign (above), we don't have much room anyway.

very very very quick mockup - and we'd prob have to use a rectangle instead of a square:
![sticker mockup](https://cloud.githubusercontent.com/assets/19319958/15326732/1d43c11c-1c1d-11e6-8134-2107a09f2cf4.png)

**Comment by loriramey** [comment]
A nice laminated copy of map at checkin desk and business counters (where owners are willing) + stickers on trolley signs around downtown + window clings in businesses along Main (etc) +  ...?

**Comment by loriramey** [comment]
Also, it sounds like "going green" might be a valuable element to marketing the app.
