### ISSUE TITLE
Suggestion to make the route lines easier to see.

### ISSUE THREAD

**Issue by WayneRyan** [hackgvl/trolley-tracker#161]
Amazingly cool app!!!

The yellow route is difficult to see on the yellow road lines. It would be easier if the route lines each had a border. Also, if the route lines had transparency set to something like 50% then it would be possible to increase the line width without obscuring the map under them.

**Comment by jeremywight** [comment]
Thanks for opening this up Wayne!

**Comment by WayneRyan** [comment]
You are awesome.

If you can draw lines of different thickness; can you get a border effect
by drawing the lines thick with one color, then drawing a thin line on top
of that with a different color?
Is that a lot of code?

Website looks good. How long have the arrows been there? I didn't see them
when I installed the app last Saturday. Showing direction of the line is a
nice improvement.

The app on my phone doesn't seem to be working now. It gives me a message
"There are no trolleys running at this time. Please..." but the web app
seems to show trolleys running.

Thank You

**Comment by bikeoid** [comment]
The web client above does draw a thin black line on top already, and that has improved the route visibility of the light colored route.

The arrows are only on the web client - they don't show on any of the apps.  I don't remember if we have  issues for the travel direction for the apps.

The development site demo with the running trolleys is a simulator with fake trolleys.  But since trolleys don't start running until 6:00 tonight, the app on your phone won't show any trolleys until then.   The phone app won't have any of these changes yes because we have to update the apps separately as we get time.
